Improved new features
Solumin/YGO-FM-FusionCalc pull request #22
Opened 2020-12-13 04:33 UTC by falsepopsky

Hi @Solumin, it's me again.

HTML / CSS:
- removed fusioncustom.css => unused file and their properties
- removed unused meta tags => robot, google fonts, br
- fixed polymerization background on fusion search and calculator page

JS: 
- data/cards.js => removed the properties of { NameColor and DescColor }, added the ritual properties into in array for a future map in the object and display in a card section like FUSION or EQUIP
- new file "functions" => in this file i moved global functions that are used in both pages (search and calculator), to prevent duplicated code.
- fusionSearch / fusionCalc => fixed the card display.
- removed test.js => that's a personal file, i should never pull that one, my mistake.

ps: let me know if u can push to github pages the final release...

2020-12-13 06:32 UTC, Solumin requested changes

2020-12-13 06:32 UTC, Solumin commented on .gitignore
> +test.js
I'd prefer if you tracked this locally rather than add it to the repo's .gitignore. (e.g. in case anyone wants to add tests in the future.)

2020-12-13 06:33 UTC, Solumin commented
Also please resolve the conflicts -- looks like this may not be based on your earlier PR?

2020-12-13 21:43 UTC, falsepopsky commented
> Also please resolve the conflicts -- looks like this may not be based on your earlier PR?

i tried to sync the forked repo with the original so many times and i got that message that says " it's up to date", but in github doesn't work, i don't know why..., i don't want to commit again because every single commit right now it's goint to this pr

2020-12-18 01:36 UTC, Solumin commented
Unfortunately I don't know either, I haven't touched git in ages...

2023-04-16 01:49 UTC, closed without merging